source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/elegion/ios-podspecs.git'

target 'ELNTextFieldFormattingKit' do

  pod 'ELNUtils', '~> 0.6.0'
  pod 'ELNValidators', '~> 0.0.10'

end

target 'Tests' do

  pod 'ELNTestUtils', '~> 0.0.1'

end
